# Generated by Django 5.0.4 on 2024-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='acknowledgement_date',
            field=models.DateTimeField(null=True),
        ),
    ]
