# Generated by Django 5.0.4 on 2024-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchase_order_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_performance',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
